//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROWeb.Authentication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROWeb.Authentication.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was successful. Conformation email was sent to your email address. Please click on conformation link in email you received to confirm your registration..
        /// </summary>
        internal static string ConformationEmailWasSentMessage {
            get {
                return ResourceManager.GetString("ConformationEmailWasSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email conformation failed!. Please contact administrator to try and resolve the issue..
        /// </summary>
        internal static string EmailConformationFailedMessage {
            get {
                return ResourceManager.GetString("EmailConformationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is verified. Please note that you will not be able to login in until your account is activated by Administrator..
        /// </summary>
        internal static string EmailVerifiedMessage {
            get {
                return ResourceManager.GetString("EmailVerifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt!.
        /// </summary>
        internal static string InvalidLoginAttemptMessage {
            get {
                return ResourceManager.GetString("InvalidLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code!.
        /// </summary>
        internal static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link was sent to your email {0}..
        /// </summary>
        internal static string PasswordResetLinkWasSentMessage {
            get {
                return ResourceManager.GetString("PasswordResetLinkWasSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed!.
        /// </summary>
        internal static string RegistrationFailedMessage {
            get {
                return ResourceManager.GetString("RegistrationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset for user {0} password succeeded!.
        /// </summary>
        internal static string ResetUserPasswordSucceededMessage {
            get {
                return ResourceManager.GetString("ResetUserPasswordSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resset password failed!.
        /// </summary>
        internal static string RessetPasswordFailedMessage {
            get {
                return ResourceManager.GetString("RessetPasswordFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account locked out!.
        /// </summary>
        internal static string UserAccountLockedOutMessage {
            get {
                return ResourceManager.GetString("UserAccountLockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email {0} already registered!.
        /// </summary>
        internal static string UserAlreadyRegisteredMessage {
            get {
                return ResourceManager.GetString("UserAlreadyRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in!.
        /// </summary>
        internal static string UserLoggedInMessage {
            get {
                return ResourceManager.GetString("UserLoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged out!!.
        /// </summary>
        internal static string UserLoggedOutMessage {
            get {
                return ResourceManager.GetString("UserLoggedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not found!.
        /// </summary>
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
    }
}
