// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROWeb.Data;

#nullable disable

namespace PROWeb.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240128123758_PRO_Office_Id_Update")]
    partial class PRO_Office_Id_Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROWeb.Data.Models.ActivityLog", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActivityId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentNo")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ConstituencyNo")
                        .HasColumnType("int");

                    b.Property<string>("HouseNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsBogus")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("ParishNo")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("AssessmentNo");

                    b.HasIndex("ConstituencyNo");

                    b.HasIndex("ParishNo");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("PROWeb.Data.Models.AssessmentFlag", b =>
                {
                    b.Property<int>("AssessmentFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentFlagId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("FlagDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Short")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AssessmentFlagId");

                    b.ToTable("AssessmentFlags");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Birth", b =>
                {
                    b.Property<int>("BirthId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BirthId");

                    b.ToTable("Births");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Constituency", b =>
                {
                    b.Property<int>("ConstituencyNo")
                        .HasColumnType("int");

                    b.Property<string>("BogusNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConstituencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConstituencyNo");

                    b.ToTable("Constituencies");
                });

            modelBuilder.Entity("PROWeb.Data.Models.ConstituencyBoundary", b =>
                {
                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("float");

                    b.Property<string>("ConstituencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geometry")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConstituencyId");

                    b.ToTable("ConstituencyBoundaries");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RegistryYear")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("PersonId", "RegistryYear");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PROWeb.Data.Models.DriverLicense", b =>
                {
                    b.Property<string>("DriverLicenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssessmentNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DriverLicenseId");

                    b.ToTable("DriverLicenses");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Eligible", b =>
                {
                    b.Property<DateTime?>("BirthDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthId")
                        .HasColumnType("int");

                    b.Property<string>("BirthLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DriverLicenseAssessmentLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("DriverLicenseAssessmentLongitude")
                        .HasColumnType("float");

                    b.Property<int?>("DriverLicenseAssessmentNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DriverLicenseAuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseConstituencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverLicenseConstituencyNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DriverLicenseDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseGender")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DriverLicenseHouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseLicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseParishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicensePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicensePostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImmigrationAuditAddDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ImmigrationAuditChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ImmigrationDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImmigrationFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmigrationGender")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("ImmigrationId")
                        .HasColumnType("int");

                    b.Property<bool?>("ImmigrationIsDeceased")
                        .HasColumnType("bit");

                    b.Property<string>("ImmigrationLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmigrationMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmigrationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImmigrationStatusAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImmigrationStatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SortIndex")
                        .HasColumnType("int");

                    b.ToTable("EligiblePoll", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PROWeb.Data.Models.FormType", b =>
                {
                    b.Property<int>("FormTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormTypeId");

                    b.ToTable("FormTypes");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Immigration", b =>
                {
                    b.Property<int>("ImmigrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImmigrationId"));

                    b.Property<DateTime>("AuditAddDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("ImmigrationRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StatusAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImmigrationId");

                    b.ToTable("Immigrations");
                });

            modelBuilder.Entity("PROWeb.Data.Models.OldPROUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanChangeFormStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRunReports")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSearchRegistrySnapshots")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdateVoterRegistration")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUseAdministration")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OldPROUsers");
                });

            modelBuilder.Entity("PROWeb.Data.Models.PROOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address4")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssistantName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ElectionYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NextAdvancedPollDate")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("NextElectionsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PO1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PO2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PO3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegisterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("YearEndDay")
                        .HasColumnType("int");

                    b.Property<int>("YearEndMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PROOffices");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Parish", b =>
                {
                    b.Property<int>("ParishNo")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ParishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParishNo");

                    b.ToTable("Parishes");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int?>("AssessmentNo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("BermudianStatusGranted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirthId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommonwealthCitizen")
                        .HasColumnType("bit");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicense")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FormTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("ImmigrationId")
                        .HasColumnType("int");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsBermudianStatusGranted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewLastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OldAssessmentNo")
                        .HasColumnType("int");

                    b.Property<string>("PhoneHome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneMobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneWork")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RegisteredAsElector")
                        .HasColumnType("bit");

                    b.Property<int>("RegistrationOriginId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistryYear")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("VoterId")
                        .HasColumnType("int");

                    b.Property<bool>("WasBornIn")
                        .HasColumnType("bit");

                    b.HasKey("RegistrationId");

                    b.HasIndex("AssessmentNo");

                    b.HasIndex("CountryId");

                    b.HasIndex("OldAssessmentNo");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("PROWeb.Data.Models.RegistrationOrigin", b =>
                {
                    b.Property<int>("RegistrationOriginId")
                        .HasColumnType("int");

                    b.Property<string>("OriginDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RegistrationOriginId");

                    b.ToTable("RegistrationOrigins");
                });

            modelBuilder.Entity("PROWeb.Data.Models.RegistrationStatus", b =>
                {
                    b.Property<int>("RegistrationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationStatusId"));

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RegistrationStatusId");

                    b.ToTable("RegistrationStatuses");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Voter", b =>
                {
                    b.Property<int>("VoterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoterId"));

                    b.Property<int>("RegistryYear")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BermudianStatusGranted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirthID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CommonwealthCitizen")
                        .HasColumnType("bit");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<string>("DriverLicense")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("ImmigrationID")
                        .HasColumnType("int");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("IsBermudianStatusGranted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneHome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneMobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneWork")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RegisteredAsElector")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("WasBornIn")
                        .HasColumnType("bit");

                    b.HasKey("VoterId", "RegistryYear");

                    b.HasIndex("AssessmentNo");

                    b.HasIndex("CountryId");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("PROWeb.Data.Models.VoterFlag", b =>
                {
                    b.Property<int>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlagId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("FlagDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("GraydOutInReports")
                        .HasColumnType("bit");

                    b.Property<bool>("Ineligible")
                        .HasColumnType("bit");

                    b.Property<string>("Short")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("FlagId");

                    b.ToTable("VoterFlags");
                });

            modelBuilder.Entity("PROWeb.Data.Models.VoterHistory", b =>
                {
                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.Property<int>("RegistryYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoterId", "RegistryYear", "Created");

                    b.ToTable("VoterHistories");
                });

            modelBuilder.Entity("PROWeb.Data.Models.VoterHistoryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistryYear")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoterId", "RegistryYear", "Created");

                    b.ToTable("VoterHistoryFields");
                });

            modelBuilder.Entity("VoterVoterFlag", b =>
                {
                    b.Property<int>("FlagId")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.Property<int>("RegistryYear")
                        .HasColumnType("int");

                    b.HasKey("FlagId", "VoterId", "RegistryYear");

                    b.HasIndex("VoterId", "RegistryYear");

                    b.ToTable("VoterVoterFlag");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Assessment", b =>
                {
                    b.HasOne("PROWeb.Data.Models.Constituency", "Constituency")
                        .WithMany("Assessments")
                        .HasForeignKey("ConstituencyNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROWeb.Data.Models.Parish", "Parish")
                        .WithMany("Assessments")
                        .HasForeignKey("ParishNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Parish");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Document", b =>
                {
                    b.HasOne("PROWeb.Data.Models.Voter", "Voter")
                        .WithMany("Documents")
                        .HasForeignKey("PersonId", "RegistryYear")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Registration", b =>
                {
                    b.HasOne("PROWeb.Data.Models.Assessment", "Assessment")
                        .WithMany("Registrations")
                        .HasForeignKey("AssessmentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROWeb.Data.Models.Country", "Country")
                        .WithMany("Registrations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROWeb.Data.Models.Assessment", "OldAssessment")
                        .WithMany("OldRegistrations")
                        .HasForeignKey("OldAssessmentNo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Assessment");

                    b.Navigation("Country");

                    b.Navigation("OldAssessment");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Voter", b =>
                {
                    b.HasOne("PROWeb.Data.Models.Assessment", "Assessment")
                        .WithMany("Voters")
                        .HasForeignKey("AssessmentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROWeb.Data.Models.Country", "Country")
                        .WithMany("Voters")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PROWeb.Data.Models.VoterHistory", b =>
                {
                    b.HasOne("PROWeb.Data.Models.Voter", "Voter")
                        .WithMany("VoterHistories")
                        .HasForeignKey("VoterId", "RegistryYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("PROWeb.Data.Models.VoterHistoryField", b =>
                {
                    b.HasOne("PROWeb.Data.Models.VoterHistory", "VoterHistory")
                        .WithMany("Fields")
                        .HasForeignKey("VoterId", "RegistryYear", "Created")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoterHistory");
                });

            modelBuilder.Entity("VoterVoterFlag", b =>
                {
                    b.HasOne("PROWeb.Data.Models.VoterFlag", null)
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoterVoterFlag_VoterFlags_FlagId");

                    b.HasOne("PROWeb.Data.Models.Voter", null)
                        .WithMany()
                        .HasForeignKey("VoterId", "RegistryYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoterVoterFlag_Voters_VoterId_RegistryYear");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Assessment", b =>
                {
                    b.Navigation("OldRegistrations");

                    b.Navigation("Registrations");

                    b.Navigation("Voters");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Constituency", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Country", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Voters");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Parish", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("PROWeb.Data.Models.Voter", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("VoterHistories");
                });

            modelBuilder.Entity("PROWeb.Data.Models.VoterHistory", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
