@host = http://localhost:5298
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmVzb3VyY2VzVXNlciIsImp0aSI6IjQ4YTBhODUzLWEzYmQtNGI5Yi05YTU0LWFiMWRmNTBhYjE0MiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBST1dlYlJlc291cmNlcyIsImV4cCI6MTc0NjM1MzQwNiwiaXNzIjoiUHJvV2ViU2VydmljZSIsImF1ZCI6IlByb1dlYlNlcnZpY2UuVXNlcnMifQ.DdBqeOrMbd6MmFhCaAQlTIF9pdcqW34tJ1Rt_8XBhmo
@apiKey = 6CBxzdYcEgNDrRhMbDpkBF7e4d4Kib46dwL9ZE5egiL0iL5Y3dzREUBSUYVUwUkN

###

GET {{host}}/tcd-photos?name=pocketftpSmall.png
X-API-Key: {{apiKey}}

###
